#  run with `ansible-playbook deploy-playbook.yaml` 
#  check config with `ansible-playbook deploy-playbook.yaml --syntax-check `
---
- hosts: all 
  remote_user: interaction 
  vars:
    app_root: /home/interaction/ftp/blog
  tasks:
    # do i have to add a mkdir task first?
    # - name: kill myblog binary
    #   shell: ps -ef | grep myblog | grep -v grep | awk '{print $2}' | xargs kill

    - name: copy build files
      synchronize: 
        src: ../frontend/build 
        dest: "{{app_root}}"
        delete: yes 
        recursive: yes

    - name: copy public files
      synchronize: 
        src: ../public 
        dest: "{{app_root}}"
        delete: yes 
        recursive: yes

    - name: copy mdroot files
      synchronize:
        src: ../mdroot 
        dest: "{{app_root}}"
        delete: yes 
        recursive: yes 
        rsync_opts: "--exclude=.git"
      
    # - name: start_myblog_binary
    #   shell: nohup ./myblog > log.txt &
    #   args:
    #     chdir: "{{app_root}}"
